// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALRW2e_5U1gRc0A3kcqd37LQuKZfXk6eY',
    appId: '1:947331738038:web:ce26cf1fc769d6904a7917',
    messagingSenderId: '947331738038',
    projectId: 'financial-b5f91',
    authDomain: 'financial-b5f91.firebaseapp.com',
    storageBucket: 'financial-b5f91.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEOgzf_KecO3gYrnQkz4LwWydMZljFUSQ',
    appId: '1:947331738038:android:b4bc427bb9e6c06d4a7917',
    messagingSenderId: '947331738038',
    projectId: 'financial-b5f91',
    storageBucket: 'financial-b5f91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbTkDIShDRnuXvlgCX2X3wYvm5cVFO-Hw',
    appId: '1:947331738038:ios:8be87f07a116ff384a7917',
    messagingSenderId: '947331738038',
    projectId: 'financial-b5f91',
    storageBucket: 'financial-b5f91.appspot.com',
    iosBundleId: 'com.example.financialapp',
  );
}
